### ISSUE TITLE
Add ability to get game log for a given player & season

### ISSUE THREAD

**Issue by jaebradley** [jaebradley/basketball_reference_web_scraper#101]
https://www.basketball-reference.com/players/e/embiijo01/gamelog/2019

**Comment by ntsirakis** [comment]
@jaebradley are you still working this? Was looking to contribute.

**Comment by jaebradley** [comment]
@ntsirakis I have not been actively working on this - I saw #114, thanks for the contribution and I'll take a look.

I'm in the middle of a refactor around how parsing logic is structured, so I might ask you to refactor your work after that parsing logic work is merged or I might accept your contribution but then edit it on top of the parsing logic refactor (just as a head's up).

Thanks again for your contribution!

**Comment by ntsirakis** [comment]
Not a problem either way! I’ll keep an eye out.

**Comment by jaebradley** [comment]
Closed by #129
