### ISSUE TITLE
Add boolean didStart flag to player_box_score

### ISSUE THREAD

**Issue by KevinSetayesh** [jaebradley/basketball_reference_web_scraper#106]
Hey thanks for building this it's very useful. Would you be able to add a flag in the player_box_score output that describes whether the player started that game or not, thanks

**Comment by jaebradley** [comment]
@KevinSetayesh this is a good idea!

I think it's something that can be implemented - let me see how long it'll take.

Note for myself - look for this `aria-label` when scraping?

![image](https://user-images.githubusercontent.com/8136030/67989357-ce651f80-fbef-11e9-8bb5-b1a54c7d4c77.png)

**Comment by Vinnetou** [comment]
Hey @jaebradley, the original script is mega useful, thanks!
I would love to add exactly what @KevinSetayesh is asking for, did you manage to implement it in the end?

**Comment by jaebradley** [comment]
@Vinnetou I have not implemented it yet, but getting your feedback on it's usefulness gives me even more incentive to implement it.

Thanks for providing that feedback and hopefully I can deliver something sooner rather than later.

I appreciate your patience.

**Comment by jaebradley** [comment]
Actually, I misspoke - I thought you were talking about a game's Box Score Page like https://www.basketball-reference.com/boxscores/201910220TOR.html (which is what my prior screenshot was referencing).

But you'll notice that the Daily Leaders Page (like https://www.basketball-reference.com/friv/dailyleaders.fcgi?month=02&day=28&year=2020), which is what the `player_box_score` output fetches, has no field that indicates if a player started or not.

I'd prefer to _not_ collect player box scores by iterating over every single game's Box Score Page for a given day vs. making a single request to the Daily Leaders Page.

So until Basketball Reference adds the concept of starting to the Daily Leaders Page, I won't deliver on this feature request.
