### ISSUE TITLE
No win or loss on team box score

### ISSUE THREAD

**Issue by garfjohnson** [jaebradley/basketball_reference_web_scraper#126]
Hello,

When accessing the team box scores, there's no outcome column.

Thanks!

**Comment by jaebradley** [comment]
@garfjohnson thanks for opening this issue - I can definitely see the value in adding an outcome field to the dictionary.

I think I can parse the `.game_summary.nohover.current` class name to get the loser / winner for a particular game.

![image](https://user-images.githubusercontent.com/8136030/73103680-9bff5180-3ec2-11ea-97c6-a87939cf88c1.png)

**Comment by garfjohnson** [comment]
That would be fantastic!

**Comment by jaebradley** [comment]
@garfjohnson this should now be implemented in `4.6.0`

![image](https://user-images.githubusercontent.com/8136030/73230282-ad5a8f00-414a-11ea-88fc-13ae770e1b2a.png)

![image](https://user-images.githubusercontent.com/8136030/73230318-c9f6c700-414a-11ea-963d-bba0f95ee35a.png)
