### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by LMSlaugh** [jaebradley/basketball_reference_web_scraper#173]
Cannot parse characters with accent marks, i.e. /u010d, /u0101

For an example see rows 47 of 
https://www.basketball-reference.com/leagues/NBA_2019_advanced.html

**Comment by LMSlaugh** [comment]
Issue appears to be constrained to Windows machines. Suggest changing line 184 of writers.py to:
        with open(options.file_path, options.mode.value, newline="", encoding="utf-8") as csv_file:

**Comment by jaebradley** [comment]
Sorry about the delay on this @LMSlaugh.

I have a Mac machine so I have been unable to reproduce.

I'll take a look at your suggestion shortly and hopefully have a fix soon.

Appreciate your patience and sorry again for the delay.

**Comment by LMSlaugh** [comment]
No worries! I'm on Windows 10 using Python 3.6.5 and the suggested fix works for me.

Here's the error: "UnicodeEncodeError: 'charmap' codec can't encode character '\u0101' in position 21: character maps to <undefined>" Let me know if you want the full stack trace and the attempted request.

**Comment by jaebradley** [comment]
@LMSlaugh this should be resolved in the latest release -[`4.9.1`](https://github.com/jaebradley/basketball_reference_web_scraper/releases/tag/4.9.1).

In addition to hopefully resolving the issue, I switched the continuous integration service from Travis to GitHub Actions as GitHub Actions supports Windows + Python while Travis does not (for the time being).

I already had tests for outputting CSV and JSON files and was able to reproduce the issues that you were seeing locally, in the tests triggered by GitHub Actions.

##### [Example Test Failure](https://github.com/jaebradley/basketball_reference_web_scraper/runs/643016406?check_suite_focus=true)

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/8136030/81016928-60fcaa80-8e2f-11ea-8597-ce382fba2184.png">

After resolving this by adding in the `encoding` function argument you helpfully described in this issue, all tests are passing for Windows on Python 3.7.

Let me know if this hasn't resolved what you've been seeing after upgrading to `4.9.1` and I can investigate further.

Apologies again for the delay in resolving this issue.
