### ISSUE TITLE
Player Search returns ValueError Unknown league abbreviation

### ISSUE THREAD

**Issue by nycdubliner** [jaebradley/basketball_reference_web_scraper#184]
Some players trigger "ValueError: Unknown league abbreviation: None"

Reproduction instructions:
from basketball_reference_web_scraper import client
client.search(term="Alonzo Mourning")

Also happens for :
client.search(term="Dominique Wilkins")
client.search(term="Rick Barry")
(But these have no years within your supported range of years.)

Thanks you for doing the work to give us this tool. 
I really appreciate it. 
T.

**Comment by jaebradley** [comment]
Yikes - sorry about this. Am looking into this issue.

**Comment by jaebradley** [comment]
@nycdubliner sorry for the delay in getting back to you - this should be resolved in `4.9.3`.

See this `repl.it` example: https://repl.it/@jaebradley/Search-For-Players-That-Missed-Seasons#main.py

<img width="1779" alt="image" src="https://user-images.githubusercontent.com/8136030/83714799-ccd25e80-a5f9-11ea-84a9-67e34b31b51e.png">
