### ISSUE TITLE
Error: super() takes at least 1 argument(0 given) 

### ISSUE THREAD

**Issue by ahaanc** [jaebradley/basketball_reference_web_scraper#192]
For all of the methods in the client file, I'm getting this error. Is this a backward compatibility issue? Because I'm running Python version 3.8. I'm confused because it says this library only runs on Python version 3.4+. My bad if this is an easily fixable problem, I'm pretty new to python.

**Comment by jaebradley** [comment]
@ahaanc can you share a stack trace and the version of `basketball_reference_web_scraper` you've installed?

**Comment by ahaanc** [comment]
Hey actually I realized that my IDE was running an older version of python and that's why I was having that error. It works fine now. Thanks anyway!
