### ISSUE TITLE
add method to download all play-offs boxscores for particular player & year

### ISSUE THREAD

**Issue by rw30** [jaebradley/basketball_reference_web_scraper#194]
hi, 

there's a method to do it for regular season games ( client.regular_season_player_box_scores()   ) but the not for PO games. I'd appreciate if this can be added.

thanks in advance.

**Comment by jaebradley** [comment]
@rw30 sorry about the delay in resolving this - the `playoff_player_box_scores` method should be available as of `4.10.0`.
