### ISSUE TITLE
Want to get current nba season standings 

### ISSUE THREAD

**Issue by pkk-git** [jaebradley/basketball_reference_web_scraper#198]
i do not see any available methods to get the same

**Comment by jaebradley** [comment]
@pkk-git noted - though you could iterate through the `season_schedule` method and derive the standings from the game outcomes.

**Comment by jaebradley** [comment]
Just to make sure we're on the same page, you'd want data from pages like https://www.basketball-reference.com/leagues/NBA_2019_standings.html

Would it be fine to only report conference standings?

![image](https://user-images.githubusercontent.com/8136030/89700224-9a472980-d8fa-11ea-853f-0fc19ab465aa.png)

**Comment by pkk-git** [comment]
yes, data from those pages is exactly what i was looking for
and it will be more than enough to report conference standings

**Comment by jaebradley** [comment]
@pkk-git you should see the new API method `standings` as part of `4.11.0`.

You can also check out [this `repl.it` link for examples](https://repl.it/@jaebradley/Settings#main.py)

<img width="1770" alt="image" src="https://user-images.githubusercontent.com/8136030/90772962-40177280-e2c3-11ea-962a-9d4e39a054cc.png">
