### ISSUE TITLE
Play by Play Functionality

### ISSUE THREAD

**Issue by WacoHolve** [jaebradley/basketball_reference_web_scraper#221]
Hello,

Thank you for creating this wonderful package. I was trying to utilize your API to pull in the play by play info and am running into an error every time I query it. I went to bbref and it looks like the pattern is: ...boxscores/php/yyyymmdd0team_acronym which you denoted in the stack trace (below).

Attempted requests:

- `client.play_by_play(home_team='PHILADELPHIA 76ERS',
                   day=23,
                   month=12,
                   year=2020,)`

- `client.play_by_play(home_team='PHI',
                   day=23,
                   month=12,
                   year=2020,)`

Both of these fail.

Using:

- requests.get('https://www.basketball-reference.com/boxscores/pbp/202012230PHI.html') does however, return a 200.

```/Desktop/nba/venv/lib/python3.8/site-packages/basketball_reference_web_scraper/client.py in play_by_play(home_team, day, month, year, output_type, output_file_path, output_write_option, json_options)
    218     try:
    219         http_service = HTTPService(parser=ParserService())
--> 220         values = http_service.play_by_play(home_team=home_team, day=day, month=month, year=year)
    221     except requests.exceptions.HTTPError as http_error:
    222         if http_error.response.status_code == requests.codes.not_found:

~/Desktop/nba/venv/lib/python3.8/site-packages/basketball_reference_web_scraper/http_service.py in play_by_play(self, home_team, day, month, year)
     95         url = "{BASE_URL}/boxscores/pbp/{year}{month}{day}0{team_abbr}.html".format(
     96             BASE_URL=HTTPService.BASE_URL, year=year, month=add_0_if_needed(str(month)), day=add_0_if_needed(str(day)),
---> 97             team_abbr=TEAM_TO_TEAM_ABBREVIATION[home_team]
     98         )
     99         response = requests.get(url=url)

**Comment by jaebradley** [comment]
@WacoHolve sorry for the delayed reply.

If you check out [the play-by-play section of the package documentation](https://jaebradley.github.io/basketball_reference_web_scraper/api/#play-by-play) there's actually a `Team` enum that is expected by the `play_by_play` method.

<img width="795" alt="image" src="https://github.com/jaebradley/basketball_reference_web_scraper/assets/8136030/21b95809-80eb-42be-a877-cf65c283ed18">

Feel free to reopen this issue if your question is unanswered.
