### ISSUE TITLE
Not Getting Data

### ISSUE THREAD

**Issue by palkesh-imenso** [jaebradley/basketball_reference_web_scraper#237]
Hello,

We are not getting data, getting only empty array. Apis starts giving data after some 3 hours wait. And as soon as we start calling apis from our code it stops working and again have to wait 3 hours.

Please help me.

**Comment by jaebradley** [comment]
@palkesh-imenso I'm guessing you got [rate-limited](https://www.sports-reference.com/bot-traffic.html).

<img width="860" alt="image" src="https://github.com/jaebradley/basketball_reference_web_scraper/assets/8136030/be21c730-ffb4-40ee-8cb7-f0d8ac04923e">

I apologize for the delayed reply.
