### ISSUE TITLE
client.player_box_scores function no longer working.

### ISSUE THREAD

**Issue by shaileshdesai31** [jaebradley/basketball_reference_web_scraper#253]
player_box_scores gives a 404 error. Did the site discontinue the page?

**Comment by shaileshdesai31** [comment]
it looks like the path of the page changed. It was "/friv/dailyleaders.fcgi?month=01&day=19&year=2024". Now it is "friv/dailyleaders.cgi?month=01&day=19&year=2024". The change from fcgi -> cgi

**Comment by jaebradley** [comment]
@shaileshdesai31 are you still seeing this issue?

When I troubleshoot using [this replit example](https://replit.com/@jaebradley/PlayerBoxScores#main.py) I see player box scores.

<img width="1444" alt="image" src="https://github.com/jaebradley/basketball_reference_web_scraper/assets/8136030/0b7d5e49-df86-4d3b-8084-1bd331276356">

I'm going to close this for now, but feel free to re-open if you continue to see this issue.
