### ISSUE TITLE
Repeated Issue

### ISSUE THREAD

**Issue by lightsout7** [jaebradley/basketball_reference_web_scraper#267]
@shaileshdesai31 are you still seeing this issue?

When I troubleshoot using [this replit example](https://replit.com/@jaebradley/PlayerBoxScores#main.py) I see player box scores.

<img width="1444" alt="image" src="https://github.com/jaebradley/basketball_reference_web_scraper/assets/8136030/0b7d5e49-df86-4d3b-8084-1bd331276356">

I'm going to close this for now, but feel free to re-open if you continue to see this issue.

_Originally posted by @jaebradley in https://github.com/jaebradley/basketball_reference_web_scraper/issues/253#issuecomment-1993225659_

**Comment by jaebradley** [comment]
@lightsout7 you opened this issue - are you still seeing this problem?

If so, can you show and describe the erroneous behavior you'er seeing?

**Comment by jaebradley** [comment]
Closing because I haven't seen any reports of this continuing to happen.
