### ISSUE TITLE
client.players_advanced_season_totals returning 0s for games_played

### ISSUE THREAD

**Issue by esavv** [jaebradley/basketball_reference_web_scraper#295]
Hiya, big fan of this package. I noticed today that `client.players_advanced_season_totals` seems to be returning 0s for the games played stat. Not sure if this is intended, but it seems to be a change since I used this last season. Just to compare, I confirmed that `client.players_season_totals` is returning the same stat correctly.

`>>> import importlib.metadata, pandas`
`>>> from basketball_reference_web_scraper import client`
`>>> print(importlib.metadata.version('basketball_reference_web_scraper'))`
`4.15.2`
`>>> stats_dict = client.players_season_totals(2025)`
`>>> adv_dict = client.players_advanced_season_totals(2025)`
`>>> pandas.DataFrame.from_dict(stats_dict)['games_played']`
`0      17`
`1      16`
`2      18`
`3      18`
`4      17`
 `      ..`
`480     1`
`481     3`
`482     2`
`483     1`
`484     2`
`Name: games_played, Length: 485, dtype: int64`
`>>> pandas.DataFrame.from_dict(adv_dict)['games_played']`
`0      0`
`1      0`
`2      0`
`3      0`
`4      0`
`     ..`
`481    0`
`482    0`
`483    0`
`484    0`
`485    0`
`Name: games_played, Length: 486, dtype: int64`

On the [bbref page](https://www.basketball-reference.com/leagues/NBA_2025_advanced.html) the G column seems to have the right data. Not sure if I'm missing something here!

**Comment by jaebradley** [comment]
@esavv thanks for reporting this

<img width="936" alt="image" src="https://github.com/user-attachments/assets/159cbef9-5fcd-4f61-978d-08aca5f120d2">

Basketball Reference made some non-backwards-compatible changes to the `data-stat` identifier value for this column from `g` to `games`, breaking the parsing logic.

This should be resolved as of [release 4.15.3](https://github.com/jaebradley/basketball_reference_web_scraper/releases/tag/4.15.3) - feel free to reopen this issue if it is _not_ resolved after upgrading to `4.15.3`.
