### ISSUE TITLE
Update Team Abbreviations

### ISSUE THREAD

**Issue by martindonnells** [jaebradley/basketball_reference_web_scraper#69]
Currently the full season stats pull returns errors for historical teams:

"WSB" Washington Bullets 1994
"SDC" San Diego Clippers 1982

**Comment by jaebradley** [comment]
@martindonnells thanks for opening this issue!

Sorry you ran into those errors - I've yet to expand the scope of season statistics to before the `2000-20001` season as I point out in the `README`.

> This library requires Python 3.4+ and only supports seasons after the 1999-2000 season

I'll consider prioritizing work to expand the scope of supported seasons.

**Comment by martindonnells** [comment]
Thank you for the quick reply and useful information.  The current scope is plenty
