### ISSUE TITLE
Request to include date in player box score output

### ISSUE THREAD

**Issue by wsecheng** [jaebradley/basketball_reference_web_scraper#70]
Hi @jaebradley, thanks for the library! It's really neat and useful. 

I was thinking it might be useful to also include the date in the player box score output. That way you could easily aggregate by date and team to obtain team level box scores and use this data in conjunction with season schedule results (which is at the team level).

**Comment by jaebradley** [comment]
@wsecheng don't you look up player box scores by date? Seems like you might already have this information on hand for any post-fetch processing?

**Comment by jaebradley** [comment]
@wsecheng a couple thoughts

1. If what you really need is team-level box scores then maybe there's a solution that uses the table format in https://www.basketball-reference.com/boxscores/?month=01&day=01&year=2017 to get the actual team totals for each game on that date (like from this game: https://www.basketball-reference.com/boxscores/201701010ATL.html). This should cut down on the number of rows needed to be processed?
2. In general, I'm hesitant to add a field for date as it already feels like this information needs to already be identified in order to make the request in the first place.

**Comment by wsecheng** [comment]
Right, so the 'Team Totals' row is what I'm looking for. But I don't think the current web scraper pulls that row if I am correct? My thinking if that if you included a date field you could keep the existing player box score data granularity, but also easily aggregate up to the team level for that date/game if you wanted, without having to introduce a separate scraper for the team-level box score.

**Comment by jaebradley** [comment]
@wsecheng 

> But I don't think the current web scraper pulls that row if I am correct?

Yeah, that's correct - there's no API for this yet

> if you included a date field you could keep the existing player box score data granularity, but also easily aggregate up to the team level for that date/game if you wanted, without having to introduce a separate scraper for the team-level box score

This definitely makes sense, however, if somebody wants stats aggregated at the team level, it probably makes even more sense to just get that data straight from the relevant web page vs. doing the aggregation on the fly.

Maybe an API method `team_box_scores(day, month, year)`?

Finally, I want to reiterate that I don't consider adding a date field to the `player_box_scores` output a suitable solution. I think it adds superfluous data to the results and that any performance concerns that might arise from the data set you've specified are hopefully mostly alleviated by the addition of a `team_box_scores` method. Apologies if this is an unsatisfactory answer.

**Comment by jaebradley** [comment]
@wsecheng I recently published `4.1.0` that should include this `team_box_scores` API method.

Let me know if you run into issues or if it doesn't suit your needs.

If everything looks 👍 feel free to close this issue!
