### ISSUE TITLE
Non-unique player names?

### ISSUE THREAD

**Issue by bpisaacoff** [jaebradley/basketball_reference_web_scraper#74]
How are non-unique player names handled? stats.nba.com for example uses a player ID system to avoid this.

**Comment by jaebradley** [comment]
@bpisaacoff great question!

So they don't have a unique identifier per se, but you could use a player's URL (or in the screenshot below, the `data-append-csv` data attribute) as a unique identifier.

![image](https://user-images.githubusercontent.com/8136030/53684204-542a7700-3cbf-11e9-946f-9b9716ce5f18.png)

Would adding such an identifier be useful?

**Comment by bpisaacoff** [comment]
Yes I think it is a good future proofing method. Thanks!

**Comment by jaebradley** [comment]
@bpisaacoff #75 should have been merged and published as `v4.2.0`. It adds a `slug` field to each output row from player box scores and player season totals tables which represents the URI `slug` for each player's personal page on Basketball Reference.
