### ISSUE TITLE
Add default values when parsing to handle cases where text content doesn't exist or is empty string

### ISSUE THREAD

**Issue by jaebradley** [jaebradley/basketball_reference_web_scraper#78]
Like in #76

**Comment by jeffernst4** [comment]
Here's another example of it not working: https://www.basketball-reference.com/friv/dailyleaders.cgi?month=12&day=12&year=2017. Andrew Bogut has a blank for 3 pointers, so the scraper errors.

**Comment by jaebradley** [comment]
@jeffernst4 this issue should be resolved

![image](https://user-images.githubusercontent.com/8136030/57276300-febf6d00-7055-11e9-999d-d42bffec02da.png)

![image](https://user-images.githubusercontent.com/8136030/57276310-04b54e00-7056-11e9-823a-f0aefe5d3f6f.png)

* [repl.it link](https://repl.it/@jaebradley/HeavyArcticPresses)
