### ISSUE TITLE
Urllib3, requirements.txt, README, pip install

### ISSUE THREAD

**Issue by yoonjoh** [jaebradley/basketball_reference_web_scraper#82]
Following just the README as it relates to the installation of the project, I downloaded through pip install instead of the conventional git clone because of the explicit specification of the pip install capabilities, in that it was stated that this project was originally created “as an exercise for creating […] first PyPi package.” However, not long after I got the error of:“ERROR: requests 2.20.0 has requirement urllib3<1.25,>=1.21.1, but you'll have urllib3 1.25.2 which is incompatible.” 

After some research into the matter, with similar issues arising in both the project in question, as well as other projects on Github, I saw that some people suggested either downloading the urlib that would work (this was assuming you had too old of a version, instead of too new of a version, which was my issue), or also modifying the requirements.txt such that the urlib specifications could be corrected.

Ironically, when I examined the requirements.txt file, I saw that the project had actually made that exact update recently. Therefore, I realized that I should just download the project in the more conventional manner of git clone, and not pip install, since it appeared that that had not been updated as well to match the git clone download. This corrected the issue. Might I suggest, citing the discrepancy in the README, or perhaps updating the pip install capabilities as well to match the requirements.txt as it related to the urllib specifications?

**Comment by jaebradley** [comment]
@yoonjoh `v4.2.3` should no longer have the message about `urllib3 1.25.2` incompatibility.

Feel free to close if this issue has been resolved.

**Comment by jaebradley** [comment]
This seems to be resolved so I will be closing.
