### ISSUE TITLE
Open to including TOT lines in advanced stats?

### ISSUE THREAD

**Issue by cpjolicoeur** [jaebradley/basketball_reference_web_scraper#92]
Would you be open to a Pull Request which added a new argument to allowing optionally including the "TOT" (total) line rows when retrieving the advanced stats data?

https://github.com/jaebradley/basketball_reference_web_scraper/blob/v4/basketball_reference_web_scraper/parsers/players_advanced_season_totals.py#L40

Not all columns are simply "a total" sum of the individual team rows (VORP for example) and it would be great to be able to get the TOT data here for those stats where we only care about the aggregate and not just team-by-team info per player.

**Comment by jaebradley** [comment]
@cpjolicoeur I understand the reasoning behind this request, but what's giving me a little pause is that following in BBref's lead of a `TOT` `team` is not really a design pattern I'd like to follow. 

Maybe the solution is to change the `team` field to a `teams` field that outputs a set of teams when interacting with the in-memory representation of the data and a comma-separated string of team names when outputting the `JSON` and `CSV` representations of the data.

Obviously, this is a breaking change, but is potentially the cleanest solution.

Thoughts?

**Comment by cpjolicoeur** [comment]
So, you are talking about now just collecting in-memory as single dataset per player (via slug) instead of N number of datasets per player with multiple teams?

I think that makes sense and is clean from a representation and output standpoint, you just are trading off the ability to see the stats per individual team vs the total if you still wanted it that way.

Or are you suggesting supporting both, just via a new argument to determine the data structure?

**Comment by jaebradley** [comment]
@cpjolicoeur sorry about never getting back to you and for the delay in implementing this feature request.

The ability to fetch combined advanced season statistics for players was released in [`v4.9.0`](https://github.com/jaebradley/basketball_reference_web_scraper/releases/tag/4.9.0).

Here's an example `repl.it` that should illustrate this: https://repl.it/@jaebradley/Player-Advanced-Season-Totals-That-Includes-Combined-Values

**Comment by cpjolicoeur** [comment]
@jaebradley thanks for the update and follow-up on this.  Appreciate it! 👍
