### ISSUE TITLE
Missing Points Data from Season Totals

### ISSUE THREAD

**Issue by sean2chang** [jaebradley/basketball_reference_web_scraper#95]
Thanks for creating this package! I noticed season totals for all players is missing the points column. I was able to modify the script to include the points column. Let me know if you'd like me to update.

**Comment by jaebradley** [comment]
@sean2chang this is actually intentional as all the relevant information (`made_free_throws`, `made_field_goals`, and `made_three_point_field_goals`) to infer points is included in the current payload.

The idea was to avoid making the payload any larger than it should be.

**Comment by jaebradley** [comment]
@sean2chang I haven't heard back from you so I'm going to close this issue - feel free to reopen if this is still an issue for you.

**Comment by jtpavlock** [comment]
Could the calculation be added on your end to still provide the endpoint to the user then?

**Comment by jaebradley** [comment]
@sean2chang and @jtpavlock - this should have been released as of `4.7.0`
